//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vueling.Facade.Api {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vueling.Facade.Api.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All clients sent controller.
        /// </summary>
        internal static string AllASent {
            get {
                return ResourceManager.GetString("AllASent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Echoed ping.
        /// </summary>
        internal static string eP {
            get {
                return ResourceManager.GetString("eP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Echoed users.
        /// </summary>
        internal static string eU {
            get {
                return ResourceManager.GetString("eU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a api/Alumnoes.
        /// </summary>
        internal static string GetApi {
            get {
                return ResourceManager.GetString("GetApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Home Page.
        /// </summary>
        internal static string HP {
            get {
                return ResourceManager.GetString("HP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a \n.
        /// </summary>
        internal static string n {
            get {
                return ResourceManager.GetString("n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permission granted to remove client.
        /// </summary>
        internal static string OkDel {
            get {
                return ResourceManager.GetString("OkDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Response Message Header \n\n.
        /// </summary>
        internal static string ReqMsgHeader {
            get {
                return ResourceManager.GetString("ReqMsgHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Request Message Information: - \n\n.
        /// </summary>
        internal static string ReqMsgInfo {
            get {
                return ResourceManager.GetString("ReqMsgInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your response data is: .
        /// </summary>
        internal static string RespData {
            get {
                return ResourceManager.GetString("RespData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sent token.
        /// </summary>
        internal static string sT {
            get {
                return ResourceManager.GetString("sT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trying to add new client controller.
        /// </summary>
        internal static string TryNewC {
            get {
                return ResourceManager.GetString("TryNewC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unauthorized, no token sent.
        /// </summary>
        internal static string Unauth {
            get {
                return ResourceManager.GetString("Unauth", resourceCulture);
            }
        }
    }
}
