//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vueling.Infrastructure.Repository {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource3 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource3() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vueling.Infrastructure.Repository.Resource3", typeof(Resource3).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update Error.
        /// </summary>
        internal static string ErAct {
            get {
                return ResourceManager.GetString("ErAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exception error.
        /// </summary>
        internal static string ErExep {
            get {
                return ResourceManager.GetString("ErExep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There was an error with the Entity validation.
        /// </summary>
        internal static string ErExEV {
            get {
                return ResourceManager.GetString("ErExEV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid operation.
        /// </summary>
        internal static string ErExInvO {
            get {
                return ResourceManager.GetString("ErExInvO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Not supported.
        /// </summary>
        internal static string ErExNotS {
            get {
                return ResourceManager.GetString("ErExNotS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Object disposed.
        /// </summary>
        internal static string ErExObjD {
            get {
                return ResourceManager.GetString("ErExObjD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update exception.
        /// </summary>
        internal static string ErExU {
            get {
                return ResourceManager.GetString("ErExU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update currency error.
        /// </summary>
        internal static string ErExUC {
            get {
                return ResourceManager.GetString("ErExUC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entity validation error.
        /// </summary>
        internal static string ExEV {
            get {
                return ResourceManager.GetString("ExEV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid operation.
        /// </summary>
        internal static string ExInvO {
            get {
                return ResourceManager.GetString("ExInvO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Not supported exception.
        /// </summary>
        internal static string ExNotS {
            get {
                return ResourceManager.GetString("ExNotS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Object disposed exception.
        /// </summary>
        internal static string ExObjD {
            get {
                return ResourceManager.GetString("ExObjD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update exception.
        /// </summary>
        internal static string ExU {
            get {
                return ResourceManager.GetString("ExU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update currency exception.
        /// </summary>
        internal static string ExUC {
            get {
                return ResourceManager.GetString("ExUC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trying to retrieve client list.
        /// </summary>
        internal static string tryCL {
            get {
                return ResourceManager.GetString("tryCL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trying to save the client.
        /// </summary>
        internal static string trySC {
            get {
                return ResourceManager.GetString("trySC", resourceCulture);
            }
        }
    }
}
